db:
  name: root
  password: csquan253905
  ip: 127.0.0.1
  port: 3306
  database: mechanism_data_test
endpoint:
  ip: 43.198.66.226
  port: 8545
txstate:
  endpoint: http://127.0.0.1:8080
pri:
  value: bba1d1fbac697e3a2c3b48c6790be6fc223d4dd96f7495d40e5ee2b628b447c0
server:
  port: 8010

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "./log/app.log"
    level: 4
  kafka:
    enable: false
    topic: "Hui-test"
    kafka_servers:
      - "kafka-1.Hui.com:9092"
      - "kafka-2.Hui.com:9092"
      - "kafka-3.Hui.com:9092"
    level: 3

